version: '2'
services:
  prodadb:
    container_name: 'prodadb'
    image: mysql:5.6
    volumes:
      - "~/.proda/mysql:/var/lib/mysql"
      - ".:/share"
    environment:
      MYSQL_ROOT_PASSWORD: root
  proda:
    container_name: 'proda'
    command: sh -c "bundle install; rake db:create; rake db:migrate; rake db:seed; bundle exec rails s -b '0.0.0.0' -p 3001"
    privileged: true
    environment:
      PRODA_DATABASE_HOST: prodadb
      PRODA_DATABASE_USER: root
      PRODA_DATABASE_PASSWORD: root
      TERM: xterm-256color
    depends_on:
      - prodadb
    ports:
      - 0.0.0.0:3001:3001
    volumes:
      - ".:/proda"
    build:
      context: .
      dockerfile: Dockerfile

